// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_test_project/test/features/feature_auth/presentation/bloc/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_test_project/core/resources/data_state.dart' as _i3;
import 'package:flutter_test_project/features/feature_auth/domain/entities/user_entity.dart'
    as _i6;
import 'package:flutter_test_project/features/feature_auth/domain/repositories/user_repository.dart'
    as _i2;
import 'package:flutter_test_project/features/feature_auth/domain/usecases/check_email_use_case.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_1<T> extends _i1.SmartFake implements _i3.DataState<T> {
  _FakeDataState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CheckEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckEmailUseCase extends _i1.Mock implements _i4.CheckEmailUseCase {
  MockCheckEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i2.UserRepository);
  @override
  _i5.Future<_i3.DataState<_i6.UserEntity>> call(String? param) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue: _i5.Future<_i3.DataState<_i6.UserEntity>>.value(
            _FakeDataState_1<_i6.UserEntity>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i5.Future<_i3.DataState<_i6.UserEntity>>);
}
